FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ITS/SimpleWebApp/", "SimpleWebApp/"]
RUN dotnet restore "SimpleWebApp/SimpleWebApp.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet restore "SimpleWebApp/SimpleWebApp.csproj"
RUN dotnet build "SimpleWebApp/SimpleWebApp.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "SimpleWebApp/SimpleWebApp.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "SimpleWebApp.dll"]
